#!/usr/bin/env python3
"""regenerate_test_catalog.py — rebuild tests/CATALOG.md from test docstrings.

Adapted from EMR-SO/openemr/scripts/regenerate_test_catalog.py. The catalog
is the source-of-truth answer to "what tests exist for X?" — a future agent
needs to find that in <60 seconds (see testing-discipline contract).

How freshness is enforced:
    1. This script walks tests/ collecting every `def test_*` function.
    2. For each, it extracts the function's docstring (first line; if missing,
       falls back to the function name).
    3. It determines the pytest marker (`@pytest.mark.unit`, etc.) by
       parsing decorators.
    4. It writes tests/CATALOG.md as a markdown table sorted by path.
    5. `--check` mode regenerates in memory, compares to disk, exits 1 if
       different. The pre-push hook + CI gate run with --check.

Usage:
    python scripts/regenerate_test_catalog.py            # rewrite catalog
    python scripts/regenerate_test_catalog.py --check    # exit 1 if stale
    python scripts/regenerate_test_catalog.py --diff     # show what would change

Exit codes:
    0 = catalog is fresh (or was just rewritten).
    1 = --check mode and catalog is stale.
    2 = invocation / parse error.

Limitations: AST-based, runs in seconds, no pytest collection needed. Misses
parametrize cases that vary per-id (acceptable — the test function still
appears with its docstring). Class-based tests are flattened to
`ClassName::test_method` per pytest convention.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TESTS_DIR = REPO_ROOT / "tests"
CATALOG_PATH = TESTS_DIR / "CATALOG.md"

# Marker names we recognise. Anything else gets reported as "?" so the
# discrepancy surfaces. Keep in sync with pyproject.toml [tool.pytest...].
KNOWN_MARKERS = {"unit", "integration", "e2e", "eval", "live"}

CATALOG_HEADER = """\
# Test Catalog

**This file is auto-generated by `scripts/regenerate_test_catalog.py`.**
Do NOT hand-edit. To refresh:

    poetry run python scripts/regenerate_test_catalog.py

Freshness is gated by the pre-push hook + a CI workflow; a stale catalog
fails the gate. See the `testing-discipline-team-brawlers-ai` skill for
the contract this catalog enforces.

| Path | Marker | What it catches |
| --- | --- | --- |
"""


def _decorator_marker(dec: ast.expr) -> str | None:
    """Return the pytest marker name on a single decorator, or None."""
    # Forms we accept:
    #   @pytest.mark.unit
    #   @pytest.mark.unit(...)
    #   @mark.unit
    target = dec.func if isinstance(dec, ast.Call) else dec
    if not isinstance(target, ast.Attribute):
        return None
    if not isinstance(target.value, ast.Attribute):
        # Maybe `@mark.unit` (less common but legal).
        if isinstance(target.value, ast.Name) and target.value.id == "mark":
            return target.attr
        return None
    inner = target.value
    if isinstance(inner.value, ast.Name) and inner.value.id == "pytest" and inner.attr == "mark":
        return target.attr
    return None


def _collect_function_marker(
    func: ast.FunctionDef | ast.AsyncFunctionDef,
    module_markers: list[str],
    class_markers: list[str],
) -> str:
    """Determine the effective pytest marker for a test function.

    Precedence: function > class > module. If multiple known markers stack
    at the same level, prefer the first that appears in KNOWN_MARKERS in the
    canonical order (unit, integration, e2e, eval, live). If none found,
    return "?".
    """
    fn_markers = [
        _decorator_marker(d) for d in func.decorator_list if _decorator_marker(d) is not None
    ]
    # ast typing: filter Nones already done; re-cast for mypy.
    candidates = [m for m in fn_markers if m] or class_markers or module_markers
    if not candidates:
        return "?"
    for m in ("unit", "integration", "e2e", "eval", "live"):
        if m in candidates:
            return m
    # Unknown marker — surface it so author fixes either the test or this script.
    return candidates[0] or "?"


def _module_markers(tree: ast.Module) -> list[str]:
    """Module-level markers come from `pytestmark = pytest.mark.X` or list of them."""
    found: list[str] = []
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        if not any(isinstance(t, ast.Name) and t.id == "pytestmark" for t in node.targets):
            continue
        # Single marker or list of markers.
        value = node.value
        candidates = value.elts if isinstance(value, ast.List | ast.Tuple) else [value]
        for c in candidates:
            name = _decorator_marker(c)
            if name:
                found.append(name)
    return found


def _class_markers(node: ast.ClassDef) -> list[str]:
    return [m for d in node.decorator_list if (m := _decorator_marker(d)) is not None]


def _first_docstring_line(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    doc = ast.get_docstring(node, clean=True)
    if not doc:
        return ""
    first = doc.strip().splitlines()[0].strip()
    # Collapse internal pipes (table delimiter) so the markdown row survives.
    return first.replace("|", "\\|")


def collect_test_entries(tests_dir: Path) -> list[tuple[str, str, str]]:
    """Return list of (path::testid, marker, docstring-or-fallback)."""
    entries: list[tuple[str, str, str]] = []
    for py in sorted(tests_dir.rglob("test_*.py")):
        try:
            source = py.read_text(encoding="utf-8")
            tree = ast.parse(source, filename=str(py))
        except (SyntaxError, UnicodeDecodeError) as e:
            print(f"WARNING: skipping {py}: {e}", file=sys.stderr)
            continue

        mod_markers = _module_markers(tree)
        rel_path = py.relative_to(REPO_ROOT).as_posix()

        for node in tree.body:
            # Module-level test functions.
            if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef) and node.name.startswith(
                "test_"
            ):
                marker = _collect_function_marker(node, mod_markers, [])
                desc = _first_docstring_line(node) or f"(no docstring) {node.name}"
                entries.append((f"`{rel_path}::{node.name}`", marker, desc))

            # Class-based: TestFoo with test_ methods.
            elif isinstance(node, ast.ClassDef) and node.name.startswith("Test"):
                cls_markers = _class_markers(node)
                for child in node.body:
                    if isinstance(
                        child, ast.FunctionDef | ast.AsyncFunctionDef
                    ) and child.name.startswith("test_"):
                        marker = _collect_function_marker(
                            child,
                            mod_markers,
                            cls_markers,
                        )
                        desc = (
                            _first_docstring_line(child)
                            or f"(no docstring) {node.name}.{child.name}"
                        )
                        entries.append(
                            (f"`{rel_path}::{node.name}::{child.name}`", marker, desc),
                        )
    return entries


def render_catalog(entries: list[tuple[str, str, str]]) -> str:
    rows = [f"| {path} | `{marker}` | {desc} |" for path, marker, desc in entries]
    return CATALOG_HEADER + "\n".join(rows) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the on-disk catalog differs from the freshly generated one.",
    )
    mode.add_argument(
        "--diff",
        action="store_true",
        help="Print the unified diff between on-disk and freshly generated.",
    )
    args = parser.parse_args()

    if not TESTS_DIR.is_dir():
        print(f"ERROR: tests directory not found at {TESTS_DIR}", file=sys.stderr)
        return 2

    entries = collect_test_entries(TESTS_DIR)
    fresh = render_catalog(entries)

    if args.check or args.diff:
        existing = CATALOG_PATH.read_text(encoding="utf-8") if CATALOG_PATH.exists() else ""
        if existing == fresh:
            if not args.diff:
                print(
                    f"OK: {CATALOG_PATH.relative_to(REPO_ROOT)} is fresh "
                    f"({len(entries)} test entries)."
                )
            return 0
        if args.diff:
            for line in difflib.unified_diff(
                existing.splitlines(keepends=True),
                fresh.splitlines(keepends=True),
                fromfile=str(CATALOG_PATH.relative_to(REPO_ROOT)) + " (on disk)",
                tofile=str(CATALOG_PATH.relative_to(REPO_ROOT)) + " (fresh)",
            ):
                sys.stdout.write(line)
            return 1
        print(f"FAIL: {CATALOG_PATH.relative_to(REPO_ROOT)} is stale.")
        print(
            f"      Regenerate with: poetry run python {Path(__file__).relative_to(REPO_ROOT).as_posix()}"
        )
        print("      Then re-stage and commit.")
        return 1

    CATALOG_PATH.write_text(fresh, encoding="utf-8")
    print(f"OK: wrote {len(entries)} test entries to {CATALOG_PATH.relative_to(REPO_ROOT)}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
